[package]
name = "tauri_data_logger"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "1", features = ["dialog-open", "dialog-save", "fs-read-file", "fs-write-file", "path-all"] }
tauri-plugin-serialport-v1 = "0.1.0"

[build-dependencies]
tauri-build = { version = "1", features = [] }
