# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_logger/mainwindow_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 513)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox_commands = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_commands.setGeometry(QtCore.QRect(40, 290, 561, 181))
        self.groupBox_commands.setObjectName("groupBox_commands")
        self.label_port_response = QtWidgets.QLabel(self.groupBox_commands)
        self.label_port_response.setGeometry(QtCore.QRect(20, 60, 521, 61))
        self.label_port_response.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_port_response.setObjectName("label_port_response")
        self.lineEdit_port_command = QtWidgets.QLineEdit(self.groupBox_commands)
        self.lineEdit_port_command.setGeometry(QtCore.QRect(20, 29, 431, 21))
        self.lineEdit_port_command.setObjectName("lineEdit_port_command")
        self.pushButton_send_command = QtWidgets.QPushButton(self.groupBox_commands)
        self.pushButton_send_command.setGeometry(QtCore.QRect(460, 30, 81, 23))
        self.pushButton_send_command.setObjectName("pushButton_send_command")
        self.label_samples = QtWidgets.QLabel(self.groupBox_commands)
        self.label_samples.setGeometry(QtCore.QRect(500, 140, 47, 21))
        self.label_samples.setObjectName("label_samples")
        self.spinBox_log_sample_count = QtWidgets.QSpinBox(self.groupBox_commands)
        self.spinBox_log_sample_count.setGeometry(QtCore.QRect(410, 140, 81, 22))
        self.spinBox_log_sample_count.setMaximum(1000000)
        self.spinBox_log_sample_count.setProperty("value", 1000)
        self.spinBox_log_sample_count.setObjectName("spinBox_log_sample_count")
        self.pushButton_record = QtWidgets.QPushButton(self.groupBox_commands)
        self.pushButton_record.setGeometry(QtCore.QRect(310, 140, 91, 23))
        self.pushButton_record.setObjectName("pushButton_record")
        self.lineEdit_log_file = QtWidgets.QLineEdit(self.groupBox_commands)
        self.lineEdit_log_file.setGeometry(QtCore.QRect(60, 140, 231, 21))
        self.lineEdit_log_file.setObjectName("lineEdit_log_file")
        self.label_log_file = QtWidgets.QLabel(self.groupBox_commands)
        self.label_log_file.setGeometry(QtCore.QRect(20, 140, 47, 21))
        self.label_log_file.setObjectName("label_log_file")
        self.pushButton_connect_port = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_connect_port.setGeometry(QtCore.QRect(60, 240, 131, 23))
        self.pushButton_connect_port.setObjectName("pushButton_connect_port")
        self.frame_serial_settings = QtWidgets.QFrame(self.centralWidget)
        self.frame_serial_settings.setGeometry(QtCore.QRect(30, 40, 581, 101))
        self.frame_serial_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_serial_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_serial_settings.setObjectName("frame_serial_settings")
        self.groupBox_serial_settings = QtWidgets.QGroupBox(self.frame_serial_settings)
        self.groupBox_serial_settings.setGeometry(QtCore.QRect(10, 10, 561, 81))
        self.groupBox_serial_settings.setObjectName("groupBox_serial_settings")
        self.label_port_number = QtWidgets.QLabel(self.groupBox_serial_settings)
        self.label_port_number.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_port_number.setObjectName("label_port_number")
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_serial_settings)
        self.comboBox_port.setGeometry(QtCore.QRect(70, 20, 100, 22))
        self.comboBox_port.setObjectName("comboBox_port")
        self.label_baudrate = QtWidgets.QLabel(self.groupBox_serial_settings)
        self.label_baudrate.setGeometry(QtCore.QRect(150, 20, 41, 16))
        self.label_baudrate.setObjectName("label_baudrate")
        self.comboBox_baudrate = QtWidgets.QComboBox(self.groupBox_serial_settings)
        self.comboBox_baudrate.setGeometry(QtCore.QRect(190, 20, 91, 22))
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.comboBox_baudrate.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_commands.setTitle(_translate("MainWindow", "Commands and Responses"))
        self.label_port_response.setText(_translate("MainWindow", "Port response"))
        self.pushButton_send_command.setText(_translate("MainWindow", "Send"))
        self.label_samples.setText(_translate("MainWindow", "samples"))
        self.pushButton_record.setText(_translate("MainWindow", "Record"))
        self.lineEdit_log_file.setText(_translate("MainWindow", "log.txt"))
        self.label_log_file.setText(_translate("MainWindow", "Log file:"))
        self.pushButton_connect_port.setText(_translate("MainWindow", "Connect to port"))
        self.groupBox_serial_settings.setTitle(_translate("MainWindow", "Serial port settings"))
        self.label_port_number.setText(_translate("MainWindow", "Port:"))
        self.label_baudrate.setText(_translate("MainWindow", "Baud:"))
        self.comboBox_baudrate.setCurrentText(_translate("MainWindow", "115200"))
        self.comboBox_baudrate.setItemText(0, _translate("MainWindow", "921600"))
        self.comboBox_baudrate.setItemText(1, _translate("MainWindow", "460800"))
        self.comboBox_baudrate.setItemText(2, _translate("MainWindow", "115200"))
        self.comboBox_baudrate.setItemText(3, _translate("MainWindow", "57600"))
        self.comboBox_baudrate.setItemText(4, _translate("MainWindow", "19200"))
        self.comboBox_baudrate.setItemText(5, _translate("MainWindow", "9600"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
